### PR TITLE
added robohatmm1 board defs.

### PR DESCRIPTION
**Pull request by wallarug**
As requested, I am adding the board definition files for this board into the main repository.

The Robo HAT MM1 board will be listed on [CrowdSupply](https://www.crowdsupply.com/robotics-masters/robo-hat-mm1) soon and runs SeeSaw by Adafruit.

Build by:

```
make BOARD=robohatmm1
```

### CODE REVIEW

**Comment by wallarug** [comment]
This is ready for review.

**Comment by ladyada** [comment]
ok does this break compilation for other boards? please test because theres' no CI on this repo

**Comment by wallarug** [comment]
It does not impact other boards.  Only creates board definition files for this board.  No other changes.

I am still able to compile other boards still.  Is there any other checks you would like run?

**Comment by ladyada** [comment]
no thats ok!

**Pull request merged**
